upstream fastcgi_backend {
    server php:9000;
}

server {
    listen 80 default_server;
    listen 443 ssl default_server;
    server_name _;
    ssl_certificate /etc/nginx/certs/localhost.crt;
    ssl_certificate_key /etc/nginx/certs/localhost.key;

    root /var/www/html;

    location /admin {
        try_files $uri $uri/ /index.php?$args;
    }

    location /graphql {
        try_files $uri /index.php?$args;
    }

    location = /static {
        return 301 /static/;
    }

    location /static/ {
        rewrite ^/static/version\d+/(.*)$ /static/$1 last;
        alias /var/www/html/pub/static/;
        expires max;
        add_header Cache-Control "public";
    }

    location = /media {
        return 301 /media/;
    }

    location /media/ {
        root /var/www/html/pub;
        try_files $uri $uri/ /get.php?$args;
        expires 1y;
        add_header Cache-Control "public";

        location ~ ^/media/theme_customization/.*\.xml$ {
            deny all;
        }
    }

    location ~ ^/get\.php$ {
        root /var/www/html/pub;
        try_files $uri =404;
        fastcgi_pass fastcgi_backend;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_buffer_size 32k;
        fastcgi_buffers 8 32k;
    }

    location ~ ^/(index|report|404|503|health_check)\.php$ {
        root /var/www/html;
        try_files $uri =404;
        fastcgi_pass fastcgi_backend;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_buffer_size 32k;
        fastcgi_buffers 8 32k;
    }

    location / {
        proxy_pass http://nuxt:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
